server:
  port: 8082
management:
  endpoint:
    health:
      show-details: always
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - env
          - health
          - info
          - refresh
spring:
  application:
    name: corp-notifications-preferences
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      config:
        enabled: true
        prefix: corp-notifications
        default-context: 'preferences'
        format: KEY_VALUE
        watch:
          enabled: true
          delay: 600000
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer